"use client";

import { useCallback, useEffect, useState } from "react";
import { activateOntologyCalibrationGate, adoptOntologyAutoConfirmThreshold, createOntologyCalibrationGate, getOntologyCalibrationReport, getTask, listOntologyCalibrationGates, runEvaluationGate } from "./api";
import { Icon } from "./icons";
import type { BackgroundTask, OntologyCalibrationGate, OntologyCalibrationReport } from "./types";

export function OntologyCalibrationPanel({sourceId,role,refreshKey}:{sourceId?:number;role:"viewer"|"analyst"|"editor"|"admin";refreshKey:string}) {
  const [report,setReport]=useState<OntologyCalibrationReport|null>(null);const [gates,setGates]=useState<OntologyCalibrationGate[]>([]);const [manualObjects,setManualObjects]=useState("0");
  const [goldSetName,setGoldSetName]=useState("");const [goldTask,setGoldTask]=useState<BackgroundTask|null>(null);
  const [working,setWorking]=useState<"refresh"|"gold"|"gate"|"activate"|"threshold"|null>(null);const [failure,setFailure]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  const canEdit=role==="editor"||role==="admin";
  const load=useCallback(async()=>{if(!sourceId){setReport(null);setGates([]);return;}const manual=Number(manualObjects)||0;const [nextReport,nextGates]=await Promise.all([getOntologyCalibrationReport(sourceId,manual),listOntologyCalibrationGates(sourceId)]);setReport(nextReport);setGates(nextGates);setGoldSetName((current)=>nextReport.evalSets.some((item)=>item.setName===current)?current:nextReport.evalSets.find((item)=>item.setName===nextReport.evalGate.setName)?.setName||nextReport.evalSets.find((item)=>item.ready)?.setName||nextReport.evalSets[0]?.setName||"");},[sourceId,manualObjects]);
  useEffect(()=>{let cancelled=false;const timer=window.setTimeout(()=>{void load().catch((cause)=>{if(!cancelled)setFailure(errorMessage(cause));});},0);return()=>{cancelled=true;window.clearTimeout(timer);};},[load,refreshKey]);

  async function refresh(){setWorking("refresh");setFailure(null);try{await load();}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function runPostPublishGold(){if(!sourceId||!report?.draft.id||!report.draft.publishedCurrent)return;const selected=report.evalSets.find((item)=>item.setName===goldSetName);if(!selected?.ready){setFailure("所选评测集不存在或 Gold SQL 尚未补齐。");return;}setWorking("gold");setFailure(null);setMessage(null);try{let task=await runEvaluationGate(sourceId,selected.setName,report.draft.id);setGoldTask(task);for(let poll=0;poll<900&&["queued","running"].includes(task.status);poll++){await new Promise((resolve)=>window.setTimeout(resolve,1000));task=await getTask(task.id);setGoldTask(task);}if(task.status!=="succeeded")throw new Error(task.error||"发布后 Gold 语义门禁未完成");await load();setMessage(`${selected.setName} 已针对当前发布 Schema 完成语义门禁，校准证据已刷新。`);}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function createGate(){if(!sourceId||!canEdit)return;setWorking("gate");setFailure(null);setMessage(null);try{const gate=await createOntologyCalibrationGate({sourceId,manualObjectCount:Number(manualObjects)||0});setGates((items)=>[gate,...items]);setReport(gate.metrics);setMessage(gate.passed?"门禁快照已通过，管理员现在可以启用 auto_draft。":"门禁快照已保存，系统继续保持 review。");}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function activate(gate:OntologyCalibrationGate){if(role!=="admin")return;setWorking("activate");setFailure(null);setMessage(null);try{const result=await activateOntologyCalibrationGate(gate.id);setGates((items)=>items.map((item)=>item.id===gate.id?result.gate:item));setMessage("已基于复核后的最新证据启用 auto_draft。");await load();}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function adoptThreshold(){if(role!=="admin"||!sourceId||!report?.settingDraft)return;setWorking("threshold");setFailure(null);setMessage(null);try{await adoptOntologyAutoConfirmThreshold({sourceId,autoConfirmScore:report.settingDraft.autoConfirmScore,runIds:report.settingDraft.runIds,targetPrecision:report.thresholdSuggestion.targetPrecision});setMessage(`已采纳逐数据源阈值 ${report.settingDraft.autoConfirmScore}，新生成批次将冻结该值。`);await load();}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}

  return <aside className="panel ai-calibration-panel">
    <div className="panel-title"><div><h2>真实源校准门禁</h2><p>仅聚合目录未漂移的同版本批次；双检人必须不同于首轮审核人。</p></div><span className={`calibration-mode ${report?.mode||"off"}`}>{report?.mode||"off"}</span></div>
    {failure&&<p className="ai-error-copy">{failure}</p>}{message&&<p className="calibration-message">{message}</p>}
    {report?<>
      <div className="calibration-hero"><div><small>模拟自动确认准确率</small><strong>{report.quality.precision==null?"—":formatPercent(report.quality.precision)}</strong><span>{report.counts.labeledAuto}/{report.thresholds.minSamples} 个双检样本</span></div><em className={report.passed?"passed":"pending"}>{report.passed?"门禁通过":"保持 review"}</em></div>
      <div className="calibration-stats"><CalibrationStat label="候选" value={report.counts.candidates}/><CalibrationStat label="可自动" value={report.counts.autoEligible}/><CalibrationStat label="未标注" value={report.counts.unlabeledAuto}/><CalibrationStat label="选中过期" value={report.counts.staleRuns}/><CalibrationStat label="已排除过期" value={report.counts.excludedStaleRuns}/><CalibrationStat label="无效标签" value={report.counts.invalidLabels}/><CalibrationStat label="自动撤回" value={formatPercent(report.quality.autoWithdrawnRate)}/><CalibrationStat label="重复率" value={formatPercent(report.quality.duplicateRate)}/><CalibrationStat label="修改率" value={formatPercent(report.quality.humanModificationRate)}/><CalibrationStat label="补录率" value={formatPercent(report.quality.manualObjectRate)}/><CalibrationStat label="草稿发布" value={formatOptionalPercent(report.downstream.draftPublicationRate)}/><CalibrationStat label="语义执行" value={formatOptionalPercent(report.downstream.semanticExecutionRate)}/><CalibrationStat label="JOIN 失败" value={formatOptionalPercent(report.downstream.joinFailureRate)}/><CalibrationStat label="Gold 等价" value={formatOptionalPercent(report.downstream.goldEquivalenceRate)}/><CalibrationStat label="Schema 首过" value={formatOptionalPercent(report.downstream.schemaValidationPassRate)}/></div>
      <div className="calibration-conditions">{report.conditions.map((condition)=><div className={condition.passed?"passed":"failed"} key={condition.id}><Icon name={condition.passed?"check":"shield"} size={12}/><span>{condition.label}</span><em>{formatActual(condition.actual)} · {condition.target}</em></div>)}</div>
      {report.ruleSuggestions.length?<p className="ai-error-copy">规则建议：{report.ruleSuggestions.map((item)=>`${item.issueType} ${formatPercent(item.ratio)} → ${item.forcedReviewReason}`).join("；")}</p>:null}
      {report.settingDraft?<div className="calibration-gold-action"><span>逐数据源阈值建议：{report.settingDraft.autoConfirmScore}（目标 precision {formatPercent(report.thresholdSuggestion.targetPrecision)}，当前来源 {report.autoConfirmScoreSource}）</span><button onClick={()=>void adoptThreshold()} disabled={role!=="admin"||working!==null}>{working==="threshold"?"采纳中…":"采纳阈值并留痕"}</button></div>:null}
      {!report.evalGate.valid&&report.evalGate.issues.length?<p className="ai-error-copy">Gold 证据未就绪：{report.evalGate.issues.map((item)=>item.message).join("；")}</p>:null}
      <div className="calibration-gold-action"><label><span>发布后 Gold 评测集</span><select value={goldSetName} disabled={!canEdit||working!==null||!report.evalSets.length} onChange={(event)=>setGoldSetName(event.target.value)}>{report.evalSets.length?report.evalSets.map((item)=><option key={item.setName} value={item.setName}>{item.setName} · {item.goldCount}/{item.total} Gold{item.heldOutCount?` · ${item.heldOutCount} Held-out`:""}</option>):<option value="">尚无评测集</option>}</select></label><button onClick={()=>void runPostPublishGold()} disabled={!canEdit||working!==null||!report.draft.publishedCurrent||!report.evalSets.find((item)=>item.setName===goldSetName)?.ready}>{working==="gold"?"门禁运行中…":report.evalGate.valid?"重新运行发布后门禁":"运行发布后门禁"}</button>{goldTask&&working==="gold"?<small>{goldTask.currentStep||"等待后台任务"} · {goldTask.progress}%</small>:null}</div>
      <label className="calibration-manual-input"><span>人工补录对象数</span><input type="number" min={0} value={manualObjects} disabled={!canEdit} onChange={(event)=>setManualObjects(event.target.value)}/><button onClick={()=>void refresh()} disabled={working!==null}>{working==="refresh"?"计算中…":"重算"}</button></label>
      <div className="calibration-actions"><button className="primary-button" onClick={()=>void createGate()} disabled={!canEdit||working!==null}>{working==="gate"?"保存中…":"保存门禁快照"}</button>{gates[0]?.passed&&!gates[0].activatedAt?<button onClick={()=>void activate(gates[0])} disabled={role!=="admin"||working!==null}>{working==="activate"?"启用中…":"启用 auto_draft"}</button>:null}</div>
      {gates[0]&&<p className="calibration-last-gate">最近门禁 · {gates[0].passed?"通过":"未通过"}{gates[0].activatedAt?` · ${gates[0].activatedBy} 已启用`:""}</p>}
    </>:<div className="ai-empty"><Icon name="shield" size={22}/><strong>等待校准数据</strong><span>生成并审核真实源候选后，这里会显示精度与召回门禁。</span></div>}
  </aside>;
}

function CalibrationStat({label,value}:{label:string;value:number|string}){return <div><small>{label}</small><strong>{value}</strong></div>;}
function formatPercent(value:number){return `${Math.round(value*1000)/10}%`;}
function formatOptionalPercent(value:number|null){return value==null?"—":formatPercent(value);}
function formatActual(value:number|boolean|null){if(value==null)return "—";if(typeof value==="boolean")return value?"通过":"未通过";if(value>=0&&value<=1)return formatPercent(value);return Number.isInteger(value)?String(value):String(Math.round(value));}
function errorMessage(cause:unknown){return cause instanceof Error?cause.message:String(cause);}
