"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ApiError, getOntologyCatalog, getOntologySchema, getOntologySchemaDiff, getTask, importTermAnchors, listOntologySchemas, publishOntologySchema, rollbackOntologySchema, runEvaluationGate, saveOntologySchema, validateOntologySchema } from "./api";
import { Icon } from "./icons";
import { OntologyAiWorkbench } from "./ontology-ai-workbench";
import { SemanticSchemaForm } from "./semantic-schema-form";
import type { OntologyCatalog, SemanticSchema, SemanticSchemaDiff, SemanticSchemaValidation, SemanticSchemaVersion } from "./types";

type Role="viewer"|"analyst"|"editor"|"admin";

export function SemanticModelingWorkspace({sourceId,role,onPublished}:{sourceId?:number;role:Role;onPublished:()=>Promise<void>}) {
  const [versions,setVersions]=useState<SemanticSchemaVersion[]>([]);const [selected,setSelected]=useState<SemanticSchemaVersion|null>(null);const [catalog,setCatalog]=useState<OntologyCatalog|null>(null);
  const [schema,setSchema]=useState<SemanticSchema>(blankSchema());const [savedText,setSavedText]=useState("");const [jsonText,setJsonText]=useState("");const [mode,setMode]=useState<"structured"|"json">("structured");
  const [validation,setValidation]=useState<SemanticSchemaValidation|null>(null);const [diff,setDiff]=useState<SemanticSchemaDiff|null>(null);const [compareId,setCompareId]=useState<number|null>(null);
  const [workspaceMode,setWorkspaceMode]=useState<"ai"|"schema">("ai");
  const initialModeResolved=useRef(false);
  const [loading,setLoading]=useState(false);const [working,setWorking]=useState<"validate"|"save"|"publish"|"rollback"|"diff"|"gate"|null>(null);const [failure,setFailure]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  const canEdit=role==="editor"||role==="admin";const serialized=useMemo(()=>JSON.stringify(schema),[schema]);const dirty=serialized!==savedText;const published=versions.find((item)=>item.status==="published")||null;const summary=validation?.summary||selected?.validation.summary;

  const load=useCallback(async(preferredId?:number)=>{if(!sourceId){setVersions([]);setSelected(null);setCatalog(null);return;}setLoading(true);setFailure(null);try{const [items,nextCatalog]=await Promise.all([listOntologySchemas(sourceId),getOntologyCatalog(sourceId)]);setVersions(items);setCatalog(nextCatalog);if(!initialModeResolved.current){initialModeResolved.current=true;if(items.length)setWorkspaceMode("schema");}const target=items.find((item)=>item.id===preferredId)||items.find((item)=>item.status==="published")||items[0];if(target){const version=await getOntologySchema(target.id),next=version.schema||blankSchema();setSelected(version);setSchema(next);setJsonText(JSON.stringify(next,null,2));setSavedText(JSON.stringify(next));setValidation(version.validation);setDiff(null);setCompareId(version.status==="published"?null:items.find((item)=>item.status==="published")?.id||null);setMessage(null);setFailure(null);}else{const next=blankSchema();setSelected(null);setSchema(next);setJsonText(JSON.stringify(next,null,2));setSavedText("");setValidation(null);setDiff(null);setCompareId(null);setMessage("正在编辑新版本；保存后会生成不可变草稿。");setFailure(null);}}catch(cause){setFailure(errorMessage(cause));}finally{setLoading(false);}},[sourceId]);
  useEffect(()=>{initialModeResolved.current=false;},[sourceId]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer);},[load]);

  function applyVersion(version:SemanticSchemaVersion){const next=version.schema||blankSchema(),text=JSON.stringify(next);setSelected(version);setSchema(next);setJsonText(JSON.stringify(next,null,2));setSavedText(text);setValidation(version.validation);setDiff(null);setCompareId(version.status==="published"?null:versions.find((item)=>item.status==="published")?.id||null);setMessage(null);setFailure(null);}
  function startBlank(base?:SemanticSchema){const next=structuredClone(base||blankSchema());setSelected(null);setSchema(next);setJsonText(JSON.stringify(next,null,2));setSavedText("");setValidation(null);setDiff(null);setCompareId(versions.find((item)=>item.status==="published")?.id||null);setMessage("正在编辑新版本；保存后会生成不可变草稿。");setFailure(null);}
  function updateSchema(next:SemanticSchema){setSchema(next);setJsonText(JSON.stringify(next,null,2));setValidation(null);setDiff(null);setMessage(null);}
  function updateJson(value:string){setJsonText(value);setValidation(null);setDiff(null);setMessage(null);try{const parsed=JSON.parse(value);if(parsed&&typeof parsed==="object"&&!Array.isArray(parsed)){setSchema(parsed as SemanticSchema);setFailure(null);}}catch{/* 高级模式允许暂时不完整的 JSON */}}
  function syncJson(){try{const parsed=JSON.parse(jsonText);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("根节点必须是 JSON 对象");updateSchema(parsed as SemanticSchema);setJsonText(JSON.stringify(parsed,null,2));return parsed as SemanticSchema;}catch(cause){setFailure(`JSON 无法解析：${cause instanceof Error?cause.message:String(cause)}`);return null;}}
  function switchMode(next:"structured"|"json"){if(next==="structured"&&mode==="json"&&!syncJson())return;if(next==="json")setJsonText(JSON.stringify(schema,null,2));setMode(next);}
  async function validate(){if(!sourceId)return;const next=mode==="json"?syncJson():schema;if(!next)return;setWorking("validate");setFailure(null);try{const result=await validateOntologySchema(sourceId,next);setValidation(result);setMessage(result.ok?"校验通过，可以保存并发布。":`发现 ${result.errors.length} 个必须修复的问题。`);}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function save(){if(!sourceId||!canEdit)return;const next=mode==="json"?syncJson():schema;if(!next)return;setWorking("save");setFailure(null);try{const result=await saveOntologySchema(sourceId,next);const success=result.validation.ok?`草稿 v${result.version} 已保存并通过校验。`:`草稿 v${result.version} 已保存，仍有 ${result.validation.errors.length} 个问题。`;await load(result.id);setMessage(success);}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function publish(){if(!selected||dirty||!canEdit)return;setWorking("publish");setFailure(null);try{const current=versions.find((item)=>item.status==="published");if(current&&current.id!==selected.id){let preflight=await getOntologySchemaDiff(selected.id,current.id);if(preflight.evaluationImpact?.summary.requiresEvaluation){if(preflight.evaluationImpact.uncoveredChanges.length)throw new Error(`发布被阻止：${preflight.evaluationImpact.uncoveredChanges.map((item)=>item.label).join("、")} 尚无评测覆盖。`);const missing=(preflight.evaluationImpact.gateEvidence||[]).filter((item)=>!item.passed).map((item)=>item.setName);for(const setName of missing){setMessage(`正在针对候选 v${selected.version} 运行受影响评测集 ${setName}…`);await executeCandidateGate(setName);}preflight=await getOntologySchemaDiff(selected.id,current.id);setDiff(preflight);if(!preflight.evaluationImpact?.summary.readyToPublish)throw new Error("候选版本评测尚未满足发布门禁。");}}const result=await publishOntologySchema(selected.id);setValidation(result);await load(result.record.id);await onPublished();setMessage(`v${result.record.version} 已发布，旧发布版本已自动废弃。`);}catch(cause){const payload=validationFromError(cause);if(payload)setValidation(payload);setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function rollback(){if(!selected||selected.status!=="deprecated"||dirty||!canEdit)return;setWorking("rollback");setFailure(null);try{const result=await rollbackOntologySchema(selected.id);setValidation(result);await load(result.record.id);await onPublished();setMessage(`已从 v${result.rolledBackFrom} 回滚到 v${result.record.version}；回滚前已按当前物理结构重新校验。`);}catch(cause){const payload=validationFromError(cause);if(payload)setValidation(payload);setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function choose(id:number){setLoading(true);setFailure(null);try{applyVersion(await getOntologySchema(id));}catch(cause){setFailure(errorMessage(cause));}finally{setLoading(false);}}
  async function compare(){if(!selected||!compareId)return;setWorking("diff");setFailure(null);try{setDiff(await getOntologySchemaDiff(selected.id,compareId));}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}
  async function executeCandidateGate(setName:string){if(!sourceId||!selected)throw new Error("缺少候选 Schema 版本");let task=await runEvaluationGate(sourceId,setName,selected.id);for(let poll=0;poll<900&&["queued","running"].includes(task.status);poll++){await new Promise((resolve)=>window.setTimeout(resolve,1000));task=await getTask(task.id);}if(task.status!=="succeeded")throw new Error(task.error||"候选版本评测门禁未完成");}
  async function runAffectedGate(setName:string){if(!sourceId||!selected||!compareId||selected.status!=="draft")return;setWorking("gate");setFailure(null);try{await executeCandidateGate(setName);setDiff(await getOntologySchemaDiff(selected.id,compareId));setMessage(`${setName} 已针对候选 v${selected.version} 完成门禁；发布检查已刷新。`);}catch(cause){setFailure(errorMessage(cause));}finally{setWorking(null);}}

  return <div className="content sub-page semantic-modeling-page"><div className="page-header"><div><span className="section-kicker">Semantic Modeling</span><h1>业务对象建模</h1><p>{workspaceMode==="ai"?"从真实物理结构生成可审核候选，经人工确认后组装为不可变草稿。":"通过结构化表单描述对象、属性和关系；发布前会重新匹配最新表、字段与已确认 JOIN。"}</p></div><div className="header-actions"><div className="segmented modeling-workspace-toggle"><button className={workspaceMode==="ai"?"active":""} onClick={()=>setWorkspaceMode("ai")}><Icon name="spark" size={13}/>AI 生成草稿</button><button className={workspaceMode==="schema"?"active":""} onClick={()=>setWorkspaceMode("schema")}><Icon name="graph" size={13}/>版本编辑器</button></div>{workspaceMode==="schema"&&<><button className="secondary-button" onClick={()=>startBlank(schema)} disabled={!sourceId||!canEdit}><Icon name="plus" size={14}/>基于当前版本新建</button><button className="primary-button" onClick={()=>void save()} disabled={!sourceId||!canEdit||working!==null}><Icon name="plus" size={14}/>{working==="save"?"保存中…":"保存新草稿"}</button></>}</div></div>
    {!canEdit&&<Notice tone="warning" title="当前身份为只读模式" body="viewer 和 analyst 可以查看版本、差异与校验结果；保存、校验和发布需要 editor 或 admin。"/>}{failure&&<Notice tone="danger" title="操作未完成" body={failure}/>} {message&&<Notice tone="success" title="状态更新" body={message}/>} 
    {workspaceMode==="ai"?<OntologyAiWorkbench sourceId={sourceId} catalog={catalog} role={role} onApplied={async(draftId)=>{await load(draftId);setWorkspaceMode("schema");}} onOpenEditor={()=>setWorkspaceMode("schema")}/>:<><div className="metric-grid"><Metric label="当前发布" value={published?`v${published.version}`:"—"} meta={published?formatDate(published.publishedAt):"尚未发布"} tone="cyan"/><Metric label="业务对象" value={String(published?.validation.summary.objectTypes||0)} meta={`发布版 · ${published?.validation.summary.properties||0} 个属性`} tone="violet"/><Metric label="语义关系" value={String(published?.validation.summary.linkTypes||0)} meta="绑定已确认物理 JOIN" tone="green"/><Metric label="版本历史" value={String(versions.length)} meta={`${versions.filter((item)=>item.status==="draft").length} 个草稿`} tone="amber"/></div><TermAnchorManager sourceId={sourceId} role={role} count={catalog?.termAnchors?.length||0} onImported={async()=>{if(sourceId)setCatalog(await getOntologyCatalog(sourceId));}}/>
    <div className="semantic-modeling-layout"><aside className="panel ontology-version-panel"><div className="panel-title"><div><h2>Schema 版本</h2><p>每次保存生成新版本，历史内容不会被覆盖。</p></div><span>{loading?"读取中…":`${versions.length} 个`}</span></div><div className="ontology-version-list">{versions.length?versions.map((item)=><button key={item.id} className={selected?.id===item.id?"selected":""} onClick={()=>void choose(item.id)}><span className={`version-status ${item.status}`}>{statusLabel(item.status)}</span><div><strong>v{item.version} · {item.schemaName}</strong><small>{item.validation.summary.objectTypes} 对象 · {item.validation.summary.linkTypes} 关系 · {item.createdBy}</small></div><em className={item.validation.ok?"valid":"invalid"}>{item.validation.ok?"有效":`${item.validation.summary.errorCount} 错误`}</em></button>):<div className="version-empty"><Icon name="graph" size={24}/><strong>还没有业务对象版本</strong><span>从右侧表单开始建模并保存草稿。</span></div>}</div>{selected&&versions.length>1?<DiffPanel versions={versions} selected={selected} compareId={compareId} diff={diff} working={working==="diff"} gateRunning={working==="gate"} onCompareId={setCompareId} onCompare={()=>void compare()} onRunGate={(setName)=>void runAffectedGate(setName)}/>:null}</aside>
      <section className="panel ontology-schema-editor"><div className="schema-editor-head"><div><span className="section-kicker">{selected?`VERSION ${selected.version}`:"NEW VERSION"}</span><h2>{schema.displayName||schema.name||"未命名本体"}{dirty&&<em>未保存</em>}</h2></div><div className="modeling-view-toggle segmented"><button className={mode==="structured"?"active":""} onClick={()=>switchMode("structured")}>结构化</button><button className={mode==="json"?"active":""} onClick={()=>switchMode("json")}>JSON 高级</button></div><div><button onClick={()=>void validate()} disabled={!sourceId||!canEdit||working!==null}>{working==="validate"?"校验中…":"运行校验"}</button>{selected?.status==="deprecated"?<button className="rollback-button" onClick={()=>void rollback()} disabled={dirty||!canEdit||!selected.validation.ok||working!==null}><Icon name="refresh" size={13}/>{working==="rollback"?"回滚中…":"回滚到此版本"}</button>:<button className="publish-button" onClick={()=>void publish()} disabled={!selected||selected.status!=="draft"||dirty||!canEdit||!selected.validation.ok||working!==null}><Icon name="check" size={13}/>{selected?.status==="published"?"当前已发布":working==="publish"?"发布中…":"发布此版本"}</button>}</div></div>{mode==="structured"?<><SemanticSchemaForm schema={schema} catalog={catalog} validation={validation} disabled={!canEdit} onChange={updateSchema}/><div className="structured-validation"><ValidationSummary validation={validation} summary={summary}/></div></>:<div className="schema-editor-body"><textarea aria-label="业务对象 Schema JSON" spellCheck={false} value={jsonText} readOnly={!canEdit} onChange={(event)=>updateJson(event.target.value)}/><div className="schema-validation-panel"><ValidationSummary validation={validation} summary={summary}/></div></div>}</section></div>
    </>}
  </div>;
}

function DiffPanel({versions,selected,compareId,diff,working,gateRunning,onCompareId,onCompare,onRunGate}:{versions:SemanticSchemaVersion[];selected:SemanticSchemaVersion;compareId:number|null;diff:SemanticSchemaDiff|null;working:boolean;gateRunning:boolean;onCompareId:(id:number)=>void;onCompare:()=>void;onRunGate:(setName:string)=>void}){const targets=versions.filter((item)=>item.id!==selected.id);return <section className="version-diff-panel"><div><strong>版本差异</strong><span>比较 v{selected.version} 与</span></div><div className="diff-picker"><select aria-label="选择比较版本" value={compareId||""} onChange={(event)=>onCompareId(Number(event.target.value))}><option value="">选择版本</option>{targets.map((item)=><option key={item.id} value={item.id}>v{item.version} · {statusLabel(item.status)}</option>)}</select><button disabled={!compareId||working||gateRunning} onClick={onCompare}>{working?"比较中…":"比较"}</button></div>{diff?<><div className="diff-summary"><span className="breaking">{diff.summary.breaking} 破坏性</span><span>{diff.summary.added} 新增</span><span>{diff.summary.removed} 删除</span><span>{diff.summary.changed} 变更</span></div><div className="diff-list">{diff.changes.length?diff.changes.map((item,index)=><article className={item.impact} key={`${item.path}-${index}`}><span>{changeLabel(item.change)}</span><div><strong>{item.label}</strong><p>{item.detail}</p><code>{item.path}</code></div></article>):<div className="diff-empty">两个版本的业务契约一致。</div>}</div><ImpactPanel impact={diff.evaluationImpact} canRun={selected.status==="draft"} running={gateRunning} onRunGate={onRunGate}/></>:<p className="diff-help">比较对象、属性、映射和关系变化；删除、类型、主键与映射变化会标记为破坏性。</p>}</section>;}
function ImpactPanel({impact,canRun,running,onRunGate}:{impact:SemanticSchemaDiff["evaluationImpact"];canRun:boolean;running:boolean;onRunGate:(setName:string)=>void}){if(!impact)return null;if(!impact.summary.requiresEvaluation)return <div className="impact-clear"><Icon name="check" size={14}/>没有需要回归评测的破坏性或待审查变更。</div>;const evidence=new Map((impact.gateEvidence||[]).map((item)=>[item.setName,item]));return <section className="impact-panel"><div><strong>评测依赖影响</strong><span>{impact.summary.readyToPublish?"门禁已就绪":`${impact.summary.affectedCases} 用例 · ${impact.summary.affectedSets} 集合 · ${impact.summary.uncoveredChanges} 未覆盖变更`}</span></div>{impact.affectedCases.length?<div>{impact.affectedCases.map((item)=><article key={item.id}><span>{item.setName}</span><div><strong>{item.question}</strong><small>{item.reasons.join("；")}</small></div></article>)}</div>:<p>没有评测用例命中这些变更；发布前应先补充覆盖用例。</p>}{impact.affectedSets.map((setName)=><div className="impact-gate-row" key={setName}><span>{setName}</span><em>{evidence.get(setName)?.passed?"候选版本门禁已通过":"等待候选版本门禁"}</em>{canRun&&!evidence.get(setName)?.passed?<button disabled={running} onClick={()=>onRunGate(setName)}>{running?"运行中…":"运行受影响评测"}</button>:null}</div>)}{impact.uncoveredChanges.length?<p className="impact-warning">未覆盖：{impact.uncoveredChanges.map((item)=>item.label).join("、")}</p>:null}{impact.summary.subtypeRootCoverageMissing?<p className="impact-warning">层级或判别条件发生变化，但当前 Gold SQL 门禁没有任何以子类型为 rootObject 的语义评测，请补充用例后重跑门禁。</p>:null}</section>}
function ValidationSummary({validation,summary}:{validation:SemanticSchemaValidation|null;summary:SemanticSchemaValidation["summary"]|undefined}){if(!validation)return <div className="validation-empty"><Icon name="shield" size={25}/><strong>等待校验</strong><span>修改后运行校验，问题会同时标记在结构化字段与校验清单中。</span>{summary&&<small>{summary.objectTypes} 个对象 · {summary.properties} 个属性 · {summary.linkTypes} 条关系</small>}</div>;const issues=[...validation.errors.map((item)=>({...item,tone:"error"})),...validation.warnings.map((item)=>({...item,tone:"warning"}))];return <><div className={validation.ok?"validation-result valid":"validation-result invalid"}><Icon name={validation.ok?"check":"shield"} size={20}/><div><strong>{validation.ok?"Schema 校验通过":`${validation.errors.length} 个错误阻止发布`}</strong><span>{validation.summary.objectTypes} 对象 · {validation.summary.properties} 属性 · {validation.summary.linkTypes} 关系{validation.warnings.length?` · ${validation.warnings.length} 警告`:""}</span></div></div><div className="validation-issues">{issues.length?issues.map((issue,index)=><article className={issue.tone} key={`${issue.code}-${issue.path}-${index}`}><span>{issue.tone==="error"?"错误":"警告"}</span><div><strong>{issue.path}</strong><p>{issue.message}</p><code>{issue.code}</code></div></article>):<div className="all-clear">所有对象、属性和关系映射均有效。</div>}</div></>;}
function Metric({label,value,meta,tone}:{label:string;value:string;meta:string;tone:string}){return <div className={`metric-card ${tone}`}><small>{label}</small><strong>{value}</strong><span>{meta}</span></div>;}
function TermAnchorManager({sourceId,role,count,onImported}:{sourceId?:number;role:Role;count:number;onImported:()=>Promise<void>}){const [open,setOpen]=useState(false);const [vocabulary,setVocabulary]=useState("corp_glossary");const [csv,setCsv]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<string|null>(null);const admin=role==="admin";async function submit(){if(!sourceId||!csv.trim()||!admin)return;setBusy(true);setNotice(null);try{const result=await importTermAnchors(vocabulary,csv);await onImported();setCsv("");setNotice(`已导入 ${result.count} 个术语锚点。`);}catch(error){setNotice(errorMessage(error));}finally{setBusy(false);}}return <section className="panel term-anchor-manager"><div><span className="section-kicker">SKOS-LITE</span><strong>术语锚点 · {count}</strong><small>绑定企业词表中的稳定术语 ID，支持 exact / close / broader。</small></div><button onClick={()=>setOpen((value)=>!value)}>{open?"收起":"管理词表"}</button>{open&&<div className="term-anchor-import"><label>词表名<input value={vocabulary} disabled={!admin||busy} onChange={(event)=>setVocabulary(event.target.value)}/></label><label>CSV<textarea rows={4} placeholder="canonical_id,name_en,name_zh,category,kind,alt_labels" value={csv} disabled={!admin||busy} onChange={(event)=>setCsv(event.target.value)}/></label><button className="primary-button" disabled={!admin||busy||!csv.trim()||!vocabulary.trim()} onClick={()=>void submit()}>{admin?(busy?"导入中…":"导入 / 更新"):"仅 admin 可导入"}</button>{notice&&<small>{notice}</small>}</div>}</section>;}
function Notice({tone,title,body}:{tone:"success"|"danger"|"warning";title:string;body:string}){return <div className={`notice ${tone}`}><Icon name={tone==="success"?"check":"shield"}/><div><strong>{title}</strong><span>{body}</span></div></div>;}
function statusLabel(status:SemanticSchemaVersion["status"]){return ({draft:"草稿",published:"已发布",deprecated:"已废弃"})[status];}
function changeLabel(change:SemanticSchemaDiff["changes"][number]["change"]){return ({added:"新增",removed:"删除",changed:"修改"})[change];}
function formatDate(value:string|null){if(!value)return "—";const date=new Date(value.includes("T")?value:`${value.replace(" ","T")}Z`);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("zh-CN",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(date);}
function errorMessage(error:unknown){return error instanceof ApiError&&error.detail?`${error.message}：${error.detail}`:error instanceof Error?error.message:"发生未知错误";}
function validationFromError(error:unknown){if(!(error instanceof ApiError)||error.status!==422||!error.payload||typeof error.payload!=="object")return null;const payload=error.payload as Partial<SemanticSchemaValidation>;return Array.isArray(payload.errors)&&Array.isArray(payload.warnings)&&payload.summary?payload as SemanticSchemaValidation:null;}
function blankSchema():SemanticSchema{return {name:"business_ontology",displayName:"业务对象本体",description:"描述当前数据源中的核心业务对象与关系",objectTypes:[{apiName:"example_object",displayName:"示例对象",description:"请替换为真实业务对象",primaryKey:"id",properties:[{apiName:"id",displayName:"业务主键",type:"integer",required:true,mapping:{table:"",column:""}}]}],linkTypes:[]};}
