const answers = {
  repurchase: { conclusion:"企业客户复购率最高，为 31.6%，比个人客户高 10.2 个百分点。", delta:"+10.2pp", columns:[["segment","客户类型","text"],["rate","复购率","percent"],["customers","下单客户","number"]], rows:[{segment:"企业客户",rate:31.6,customers:18420},{segment:"渠道客户",rate:27.8,customers:12860},{segment:"个人客户",rate:21.4,customers:68940}], chart:{type:"bar",xKey:"segment",yKey:"rate"}, pages:["复购率","有效客户","客户-订单","时间字段口径"], tables:["crm_customer","sales_order"] },
  payment: { conclusion:"支付宝成功率最高（96.8%）；银行卡为 91.2%，需要进一步关注失败码分布。", delta:"总体 94.7%", columns:[["channel","支付渠道","text"],["rate","成功率","percent"],["attempts","支付笔数","number"]], rows:[{channel:"支付宝",rate:96.8,attempts:48200},{channel:"微信支付",rate:95.4,attempts:61380},{channel:"银行卡",rate:91.2,attempts:24620}], chart:{type:"bar",xKey:"channel",yKey:"rate"}, pages:["支付成功率","订单-支付","支付状态枚举","时间字段口径"], tables:["sales_order","payment_transaction"] },
  refund: { conclusion:"8 月 8 日退款金额为 86.4 万元，是近 30 天中位数的 2.7 倍。", delta:"2.7× 中位数", columns:[["date","日期","text"],["amount","退款金额（元）","number"],["count","退款笔数","number"]], rows:[{date:"08-05",amount:304820,count:1280},{date:"08-06",amount:318640,count:1314},{date:"08-07",amount:297180,count:1228},{date:"08-08",amount:864230,count:2891},{date:"08-09",amount:362410,count:1450},{date:"08-10",amount:331920,count:1372}], chart:{type:"line",xKey:"date",yKey:"amount"}, pages:["退款金额","订单-退款","金额单位规则","退款状态枚举"], tables:["sales_refund","sales_order"] },
  customer: { conclusion:"7 月有效客户达到 12.8 万，较 6 月增长 9.4%，连续第三个月上升。", delta:"+9.4% 环比", columns:[["month","月份","text"],["customers","有效客户","number"],["growth","环比","percent"]], rows:[{month:"2026-02",customers:98420,growth:-1.8},{month:"2026-03",customers:103680,growth:5.3},{month:"2026-04",customers:108240,growth:4.4},{month:"2026-05",customers:113560,growth:4.9},{month:"2026-06",customers:117180,growth:3.2},{month:"2026-07",customers:128240,growth:9.4}], chart:{type:"line",xKey:"month",yKey:"customers"}, pages:["有效客户","客户主表","客户月度趋势","软删除过滤规则"], tables:["crm_customer"] },
};

export function demoQuery(question) {
  const key=/退款|refund/i.test(question)?"refund":/支付|成功率|channel/i.test(question)?"payment":/复购|repurchase/i.test(question)?"repurchase":/客户|customer/i.test(question)?"customer":null;
  if(!key) return { refused:true, reason:"该问题超出演示本体覆盖范围。当前可回答客户、复购、支付和退款主题。", missingTerm:question };
  const item=answers[key];
  const sql = key==="customer" ? `SELECT DATE_FORMAT(c.certified_at, '%Y-%m') AS month, COUNT(DISTINCT c.customer_id) AS customers FROM crm_customer c WHERE c.cert_status = 1 AND c.deleted_at IS NULL AND c.is_test = 0 AND c.certified_at >= '2026-01-01' AND c.certified_at < '2026-08-01' GROUP BY DATE_FORMAT(c.certified_at, '%Y-%m') ORDER BY month LIMIT 500` : `SELECT /* 演示查询：口径由 ${item.pages[0]} 固定 */ * FROM ${item.tables.join(" JOIN ")} LIMIT 500`;
  return {id:`demo-${Date.now()}`,question,conclusion:item.conclusion,delta:item.delta,columns:item.columns.map(([key,label,type])=>({key,label,type})),rows:item.rows,chart:item.chart,evidence:{pages:item.pages,rules:["排除测试账号","排除软删除记录","金额由分换算为元"],tables:item.tables,sql,durationMs:Math.floor(720+Math.random()*360),scannedRows:key==="payment"?890432:key==="refund"?426810:key==="repurchase"?1104820:348260}};
}
